const cloths = [
  { image: "/PK-01-BLACK-FAUX-LEATHER-1.webp", name: "PK-01", category: "men", price: "$42" },
  { image: "/JC-10-BLACK-1.webp", name: "JC-10", category: "men", price: "$37" },
  { image: "/SL-03-BLACK-1.webp", name: "SG-03", category: "men", price: "$55" },
  { image: "/1_2024.webp", name: "BP-02", category: "men", price: "$29" },
  { image: "/TS-07-WHITE-1.webp", name: "TS-07", category: "men", price: "$46" },
  { image: "/TS-06.webp", name: "TT-06", category: "men", price: "$53" },
  { image: "/BL-01-BLACK-1.webp", name: "BK-01", category: "men", price: "$35" },
  { image: "/WD-02-GRAY-1.webp", name: "WD-02", category: "men", price: "$58" },
  { image: "/SL-01-GRAY-1.webp", name: "SL-01", category: "men", price: "$41" },
  { image: "/JC-11-BLACK-1.webp", name: "JC-11", category: "men", price: "$27" },
  { image: "/CT-01-LIGHT-GREEN-1.webp", name: "CT-01", category: "men", price: "$49" },
  { image: "/BG-03-GREEN-1.webp", name: "BG-03", category: "men", price: "$31" },
  { image: "/LS-03-WHITE-1.webp", name: "LS-03", category: "men", price: "$59" },
  { image: "/RC-04-BLUE-1-BLANK.webp", name: "RC-04", category: "men", price: "$24" },
  { image: "/WP-02-NAVY-1.webp", name: "WP-02", category: "men", price: "$39" },
  { image: "/JC-11-BLACK-1.webp", name: "JC-07", category: "men", price: "$47" },

  { image: "/9.webp", name: "JC-09", category: "men", price: "$34" },
  { image: "/26 EDITED.webp", name: "RC-03", category: "men", price: "$56" },
  { image: "/2.webp", name: "BB-02", category: "men", price: "$21" },
  { image: "/37.webp", name: "WD-01", category: "men", price: "$44" },
  { image: "/41.webp", name: "WP-01", category: "men", price: "$52" },
  { image: "/19.webp", name: "WB-04", category: "men", price: "$38" },
  { image: "/33.webp", name: "BB-01", category: "men", price: "$60" },
  { image: "/18 EDITED.webp", name: "JC-04", category: "men", price: "$26" },
  { image: "/66.webp", name: "TS-03", category: "men", price: "$48" },

  { image: "/HD-10.webp", name: "HD-10", category: "men", price: "$57" },
  { image: "/JC-08.webp", name: "JC-08", category: "men", price: "$32" },
  { image: "/HT-O5.webp", name: "HT-05", category: "men", price: "$40" },
  { image: "/BG-02.webp", name: "BG-02", category: "men", price: "$23" },
  { image: "/GL-01.webp", name: "GL-01", category: "men", price: "$54" },
  { image: "/Chocolate_01.webp", name: "YS-01", category: "men", price: "$45" },
  { image: "/PT-05-1.webp", name: "PT-05", category: "men", price: "$36" },
  { image: "/BX-10.webp", name: "BX-01", category: "men", price: "$28" },
  { image: "/HT-04.webp", name: "HT-04", category: "men", price: "$50" },
  { image: "/BG-01-2.webp", name: "BG-01", category: "men", price: "$33" },

  { image: "/SL-02.webp", name: "SL-02", category: "men", price: "$58" },
  { image: "/PD-01.webp", name: "PD-01", category: "men", price: "$42" },
  { image: "/HT-01.webp", name: "HT-01", category: "men", price: "$27" },
  { image: "/SG-01.webp", name: "SG-01", category: "men", price: "$55" },
  { image: "/SG-02.webp", name: "SG-02", category: "men", price: "$31" },
  { image: "/BP-01.webp", name: "BP-01", category: "men", price: "$46" },
  { image: "/JC-03.webp", name: "JC-03", category: "men", price: "$22" },
  { image: "/TS-05.webp", name: "TS-05", category: "men", price: "$59" },
  { image: "/TS-01.webp", name: "TS-01", category: "men", price: "$34" },
  { image: "/WB-01.webp", name: "WB-01", category: "men", price: "$41" },

  { image: "/SH-01.webp", name: "SH-01", category: "men", price: "$52" },
  { image: "/SP-08.webp", name: "SP-08", category: "men", price: "$30" },
  { image: "/SP-09.webp", name: "SP-09", category: "men", price: "$47" },
  { image: "/SK-01.webp", name: "SK-01", category: "men", price: "$24" },
  { image: "/ts-02-black-front.webp", name: "TS-02", category: "men", price: "$56" },
  { image: "/SP-01.webp", name: "SP-01", category: "men", price: "$38" },
  { image: "/SP-06.webp", name: "SP-06", category: "men", price: "$43" },

  { image: "/Chocolate_01.webp", name: "YS-06", category: "slides", price: "$60" },
  { image: "/ERROR.webp", name: "YS-01", category: "slides", price: "$49" },
  { image: "/YS-3.webp", name: "YS-02", category: "slides", price: "$31" },
  { image: "/YS-5.webp", name: "YS-03", category: "slides", price: "$54" },
  { image: "/YS-CHO.webp", name: "YS-04", category: "slides", price: "$26" },
  { image: "/YS-MILK.webp", name: "YS-05", category: "slides", price: "$44" },
  {image: "/YS-08.webp", name: "YS-08", category: "slides", price: "$20"},

  { image: "/SL-03-BLACK-1.webp", name: "SG-03", category: "accessories", price: "$35" },
  { image: "/1_2024.webp", name: "BP-02", category: "accessories", price: "$57" },
  { image: "/BG-03-GREEN-1.webp", name: "BG-01", category: "accessories", price: "$22" },
  { image: "/BG-01-2.webp", name: "BG-01", category: "accessories", price: "$48" },
  { image: "/HT-O5.webp", name: "HT-05", category: "accessories", price: "$41" },
  { image: "/BG-02.webp", name: "BG-02", category: "accessories", price: "$29" },
  { image: "/GL-01.webp", name: "GL-01", category: "accessories", price: "$60" },
  { image: "/HT-04.webp", name: "HT-04", category: "accessories", price: "$34" },
  { image: "/WH-01.webp", name: "WH-01", category: "accessories", price: "$51" },
  { image: "/BT-01.webp", name: "BT-01", category: "accessories", price: "$27" },
  { image: "/HT-01.webp", name: "HT-01", category: "accessories", price: "$45" },
  { image: "/SG-01.webp", name: "SG-01", category: "accessories", price: "$38" },
  { image: "/SG-02.webp", name: "SG-02", category: "accessories", price: "$56" },
  { image: "/BP-01.webp", name: "BP-01", category: "accessories", price: "$24" },

  { image: "/BR-09.webp", name: "BR-09", category: "women", price: "$50" },
  { image: "/TT-04-Black-Front.webp", name: "TT-04", category: "women", price: "$33" },
  { image: "/TT-02-Black-Front.webp", name: "TT-02", category: "women", price: "$58" },
  { image: "/BD-03_Black)_Front.webp", name: "BD-03", category: "women", price: "$42" },
  { image: "/BD-04.webp", name: "BD-04", category: "women", price: "$36" },
  { image: "/BD-10.webp", name: "BD-10", category: "women", price: "$59" },
  { image: "/RESIZED-15 (1).webp", name: "TS-04", category: "women", price: "$41" },
  { image: "/LS-04.webp", name: "LS-04", category: "women", price: "$27" },
  { image: "/ERROR-2.webp", name: "WJ-02", category: "women", price: "$53" },
  { image: "/WJ-01.webp", name: "WJ-01", category: "women", price: "$34" },
  { image: "/UW-02.webp", name: "UW-02", category: "women", price: "$60" },
  { image: "/SH-06.webp", name: "SH-06", category: "women", price: "$48" },
  { image: "/LG-13.webp", name: "LG-13", category: "women", price: "$31" },
  { image: "/LG-14.webp", name: "LG-14", category: "women", price: "$55" },
  { image: "/LG-01.webp", name: "LG-01", category: "women", price: "$25" },
  { image: "/LG-04.webp", name: "LG-04", category: "women", price: "$44" },
  { image: "/PT-10.webp", name: "PT-10", category: "women", price: "$37" },
  { image: "/HL-01.webp", name: "HL-01", category: "women", price: "$49" },
  { image: "/HL-02.webp", name: "HL-02", category: "women", price: "$28" },
  { image: "/HL-03.webp", name: "HL-03", category: "women", price: "$52" },
  { image: "/HB-01.webp", name: "HB-01", category: "women", price: "$39" },
];

export default cloths;