import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar";
import Footer from "@/component/Footer";
import { GridProvider } from "@/context/gridContext";
import { CartProvider } from "@/context/cartContext";
import CartDrawer from "@/component/cartDrawer";
import NewsLetter from "@/component/newsletter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "YEEZY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <CartProvider>
          <GridProvider>
            <Navbar />
            <CartDrawer />
            <NewsLetter />

            <main className="relative min-h-screen">
              {children}
            </main>

            <Footer />
          </GridProvider>
        </CartProvider>
      </body>
    </html>
  );
}